### ISSUE TITLE
move impatient guide to definitions repository

### ISSUE THREAD

**Issue by zjttoefs** [nexusformat/communications#18]
The build is checked in, which is no an awesome idea. I'll see if I can make this happen on build.nexusformat.org instead. That would give a neater URL to browse as well.

**Comment by zjttoefs** [comment]
One question before I think hard about setting up a build for the communications:

@prjemian is there a particular reason that the impatient guide is not part of the definitions repository?

In my view the communications repo is more for holding snapshot material not live documents. Therefore I would see the impatient guide fit nicer in the manual in the definitions.

**Comment by prjemian** [comment]
I agree it is part of the documentation.  That needs to be with the
definitions.

**Comment by mkoennecke** [comment]
Hi,

Am 08.02.2016 um 15:54 schrieb Tobias Richter <notifications@github.com<mailto:notifications@github.com>>:


One question before I think hard about setting up a build for the communications:

??? I thought communications was a private area for NIAC where we can pick up NeXus materials.
IMHO, a build makes no sense. What do you want to build there?


@prjemian<https://github.com/prjemian> is there a particular reason that the impatient guide is not part of the definitions repository?

In my view the communications repo is more for holding snapshot material not live documents. Therefore I would see the impatient guide fit nicer in the manual in the definitions.


I agree that the impatient guide should move to the manual

Regards,

    Mark
